<?php

declare(strict_types=1);

namespace Visualbuilder\FilamentDesignSystem\Mcp\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Tool;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;
use Visualbuilder\FilamentDesignSystem\Theme\Tokens;

#[Description(<<<'EOT'
    Returns the current CSS-overrides string from the overlay, ready to paste
    into the host's resources/css/filament/{panel}/theme.css.

    The graduation flow: AI iterates via write_theme_overrides; once the
    designer signs off, call export_theme_css, copy the returned CSS into the
    real theme file (so the changes land in version control), then call
    reset_overlay scope=css to clear the overlay layer.

    Read-only — does not modify any files.
    EOT)]
#[IsReadOnly]
class ExportThemeCss extends Tool
{
    public function handle(Request $request): Response
    {
        $overlay = Tokens::overlay();
        $css = $overlay['theme']['css_overrides'] ?? '';

        if (trim($css) === '') {
            return Response::json([
                'has_overrides' => false,
                'css' => '',
                'note' => 'No CSS overrides currently in the overlay. Use write_theme_overrides first.',
            ]);
        }

        $banner = "/* Generated by visualbuilder/filament-design-system on " . now()->toIso8601String() . " */\n";

        return Response::json([
            'has_overrides' => true,
            'bytes' => strlen($css),
            'css' => $banner . $css,
            'note' => 'Paste this into resources/css/filament/{panel}/theme.css after the existing imports, then call reset_overlay scope=css to clear the overlay layer.',
        ]);
    }

    public function schema(JsonSchema $schema): array
    {
        return [];
    }
}
